version: '3.8'
services:
  backend:
    container_name: backendmainservice
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'uvicorn main:app --host 0.0.0.0 --port 5000 --reload'
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - mynetwork

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    networks:
      - mynetwork
    depends_on:
      - db
      
  db:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./dbdata:/var/lib/postgresql
    ports:
      - 54321:${POSTGRES_PORT}
    networks:
      - mynetwork
      
# first create a network with the name mynetwork and then use it in the services
# run: docker network create mynetwork
networks:
  mynetwork:
    external: true
